$bg0           = rgb(282828) # #282828
$bg1           = rgb(3c3836) # #3c3836
$bg2           = rgb(504945) # #504945
$bg3           = rgb(665c54) # #665c54
$bg4           = rgb(7c6f64) # #7c6f64
$fg0           = rgb(fbf1c7) # #fbf1c7
$fg1           = rgb(ebdbb2) # #ebdbb2
$fg2           = rgb(d5c4a1) # #d5c4a1
$fg3           = rgb(bdae93) # #bdae93
$fg4           = rgb(a89984) # #a89984
$bright_red    = rgb(fb4934) # #fb4934
$bright_green  = rgb(b8bb26) # #b8bb26
$bright_yellow = rgb(fabd2f) # #fabd2f
$bright_blue   = rgb(83a598) # #83a598
$bright_purple = rgb(d3869b) # #d3869b
$bright_aqua   = rgb(8ec07c) # #8ec07c
$bright_orange = rgb(fe8019) # #fe8019
$neutral_red    = rgb(cc241d) # #cc241d
$neutral_green  = rgb(98971a) # #98971a
$neutral_yellow = rgb(d79921) # #d79921
$neutral_blue   = rgb(458588) # #458588
$neutral_purple = rgb(b16286) # #b16286
$neutral_aqua   = rgb(689d6a) # #689d6a
$neutral_orange = rgb(d65d0e) # #d65d0e
$dark_red      = rgb(722529) # #722529
$dark_green    = rgb(62693e) # #62693e
$dark_aqua     = rgb(49503b) # #49503b
$gray          = rgb(928374) # #928374

$red     = rgb(fb4934) # #fb4934
$green   = rgb(b8bb26) # #b8bb26
$yellow  = rgb(fabd2f) # #fabd2f
$blue    = rgb(83a598) # #83a598
$magenta = rgb(d3869b) # #d3869b
$aqua    = rgb(8ec07c) # #8ec07c
$orange  = rgb(fe8019) # #fe8019
$accent  = rgb(b8bb26) # #b8bb26
$urgent  = rgb(fb4934) # #fb4934
$text    = rgb(fbf1c7) # #fbf1c7
